# 核心任务
- name: MariaDB
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'mariadb_selection'
      prompt: "\nPlease choose the number for MariaDB version [ 1/2/3/4] \n\n
      1: MariaDB10.1\n
      2: MariaDB10.2\n
      3: MariaDB10.3\n
      4: MariaDB10.4\n"
      private: no
      default: 3


    - name: 'mariadb_remote_selection'
      prompt: "\nDo you want to enable MariaDB remote connection? [ 1/2 ] \n\n
      1: Enable remote connection(default)\n
      2: Disable remote connection\n"
      private: no
      default: 1

    - name: 'phpmyadmin_selection'
      prompt: "\nDo you want to install phpMyAdmin of Docker? [ 1/2 ] \n\n
      1: Yes\n
      2: No\n"
      private: no
      default: 1

  vars:
    mariadb_select:
      '1': '10.1'
      '2': '10.2'
      '3': '10.3'
      '4': '10.4'
    mariadb_version: "{{mariadb_select[mariadb_selection]}}" 

    remote_select:
      '1': True
      'y': True
      '2': ''
      'n': ''

    phpmyadmin_select:
      '1': True
      'y': True
      '2': ''
      'n': ''

    phpmyadmin_install_docker: "{{phpmyadmin_select[phpmyadmin_selection]}}" 
    mariadb_remote: "{{remote_select[remote_selection]}} or {{phpmyadmin_select[phpmyadmin_selection]}}" 
  
  
  roles:
   - {role: role_common, tags: "role_common"}   
   - {role: role_cloud, tags: "role_cloud"}
   - {role: role_mariadb, tags: "role_mariadb"}
   - {role: role_docker, tags: "role_docker", when: phpmyadmin_install_docker}
   - {role: role_docker_phpmyadmin, tags: "role_docker_phpmyadmin", when: phpmyadmin_install_docker}
   - {role: role_init_password, tags: "role_init_password"}
   - {role: role_preend, tags: "role_preend"}
   - {role: role_end, tags: "role_end"} 
